### ISSUE TITLE
Nincs ping 

### ISSUE THREAD

**Issue by hentesoposszum** [Benedek03/discord-music-bot#4]
és én ezért nagyon  szomorú vagyok

**Comment by hentesoposszum** [comment]
[nincs ping](https://pcforum.hu/tudastar/136413/net-van-ping-nincs)

**Comment by hentesoposszum** [comment]
@Kris030 @Benedek03

**Comment by Benedek03** [comment]
szar lehet

**Comment by hentesoposszum** [comment]
nem hiszem el, hogy a fejlesztő így semmibe vesz minket
